name: voxy_rat
description: Evolution Build
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  torch_light: ^1.0.1
flutter:
  uses-material-design: true
